### ISSUE TITLE
Channelcreate throws FormatException whilst returning

### ISSUE THREAD

**Issue by XoMEX** [Scordo/TS3QueryLib.Net#5]
ChannelModification c = new ChannelModification();
    c.Name = "somename";
    SingleValueResponse<uint?> res = QueryRunner.CreateChannel(c);
->throws FormatExeption for me(but the channel got created)

Callstack
all classnames start with
*TS3QueryLib.Core.Framework.dll!*
Since all classes start with that i didn't write it all the times....

->TS3QueryLib.Core.QueryRunner.CreateChannel(c)
-->return ResponseBase<SingleValueResponse<uint?>>.Parse(SendCommand(command), "cid");

->TS3QueryLib.Core.Common:Responses.ResponseBase
-->instance.FillFrom(response, additionalStates)
--->response = "cid=71\n\rnotifychannelcreated cid=71 [...]"
--->additionalStates = {object[1]}
---->additionalStates[0] = "cid"

->TS3QueryLib.Core.Common.Responses.SingleValueResponse
-->Value = list.GetParameterValue(additionalStates[0].ToString()).ChangeTypeInvariant(default(T));
--->list[0] Count = 20
---->list[0] [0] = {cid=71\n\rnotifychannelcreated}
---->list[0] [1] = {cid=71}
--->additionalStates = {object[1]}
---->additionalStates[0] = "cid"

->System.ExtensionMethods.ChangeInvariant
-->return ChangeType(sourceValue, defaultValue, CultureInfo.InvariantCluture)
--->sourceValue = "71\n\rnotifychannelcreated"
--->defaultValue = null

->System.ExtensionMethods.ChangeType
-->return (T)Convert.ChangeType(sourceValue, targetType, formatProvider)
--->sourceValue = "71\n\rnotifychannelcreated"
--->targetType = {Name = "UInt32" FullName = "System.UInt32"}

->System.FormatException
-->Message (translated by myself...) The inputstring has the wrong format.

Server Version: 3.0.10.3 (01.01.2014 17:28:39) @ Windows

**Comment by Scordo** [comment]
Hi Xomex, 

I think the real problem is a bug in TS3. 
Normally every command has a response which has 2 parts:
- body (optional)
- statusline 

In this case the the TS3 Server is sending a notification between the body and the statusline, which is wrong - I think.

Test-Response from a test of mine:
"cid=6\n\rnotifyclientmoved ctid=6 reasonid=1 invokerid=0 invokername=Server clid=5\n\rerror id=0 msg=ok\n\r"

I've fixed this for the .Net Core Version:
https://github.com/Scordo/TS3QueryLib.Net.Core/commit/5fe3c2415a158ca377d02deb4cced0e4eb69bef8

Regards,
Scordo
